/* ============================================================
   exercises.js — bibliothèque d'exercices
   Chaque fiche : muscles, objectif, consignes pas à pas,
   erreurs fréquentes, sécurité, variantes, remplacements,
   position des mains / pieds / dos, respiration, vitesse.
   ============================================================ */
"use strict";

const EX_CATS = ["Pectoraux", "Dos", "Épaules", "Bras", "Jambes", "Tronc"];

const EXOS = {
  /* ============ PECTORAUX ============ */
  "Pompes classiques": {
    cat: "Pectoraux", unit: "reps",
    muscles: ["Pectoraux", "Triceps", "Épaules (avant)", "Tronc"],
    goal: "Construire le torse et les bras — l'exercice de base pour paraître plus athlétique.",
    rest: 75, tempo: "Descente 2 s · montée 1 s, sans rebond", breath: "Inspire en descendant, souffle fort en poussant",
    hands: "Un peu plus larges que les épaules, doigts vers l'avant, sous la poitrine.",
    feet: "Joints ou légèrement écartés, sur la pointe.",
    back: "Corps rigide en planche : ventre et fessiers serrés, pas de creux lombaire.",
    steps: [
      "Place les mains au sol, un peu plus larges que les épaules.",
      "Tends les jambes : le corps forme une ligne droite des talons à la tête.",
      "Descends la poitrine vers le sol en 2 secondes, coudes à ~45° du buste.",
      "Touche presque le sol avec la poitrine, puis pousse fort pour remonter.",
      "Garde le ventre contracté pendant toute la série.",
    ],
    errors: ["Hanches qui tombent ou fesses en l'air", "Descente incomplète (demi-pompes)", "Coudes trop écartés à 90°", "Tête qui plonge vers le sol"],
    safety: ["Si les poignets tirent, serre les doigts au sol ou pose les mains sur des bouteilles solides.", "Arrête la série si le bas du dos s'écroule."],
    easier: "Pompes inclinées (mains surélevées) ou pompes sur les genoux.",
    harder: "Pompes déclinées (pieds surélevés) ou pompes lestées avec le sac.",
    replacements: ["Pompes inclinées", "Pompes sur les genoux", "Pompes mains serrées"],
    illu: ["pushup_up", "pushup_down"],
  },
  "Pompes inclinées": {
    cat: "Pectoraux", unit: "reps",
    muscles: ["Pectoraux", "Triceps", "Épaules (avant)"],
    goal: "Version plus facile de la pompe : idéale en reprise ou en fin de séance quand les bras fatiguent.",
    rest: 60, tempo: "Descente 2 s · montée 1 s", breath: "Inspire en descendant, souffle en poussant",
    hands: "Sur un support stable (table, muret, banc du bateau), largeur épaules +.",
    feet: "Au sol, en arrière, corps en ligne.",
    back: "Ligne droite épaules-bassin-talons, ventre serré.",
    steps: [
      "Pose les mains sur un support solide à hauteur de hanches ou de genoux.",
      "Recule les pieds pour que le corps soit bien incliné et droit.",
      "Descends la poitrine vers le bord du support en 2 secondes.",
      "Pousse pour revenir bras tendus sans verrouiller brutalement les coudes.",
    ],
    errors: ["Bassin cassé vers le bas", "Support instable", "Amplitude trop courte"],
    safety: ["Vérifie que le support ne glisse pas (important sur le bateau)."],
    easier: "Rapproche-toi de la verticale (mains contre un mur).",
    harder: "Baisse le support, puis passe aux pompes classiques.",
    replacements: ["Pompes classiques", "Pompes sur les genoux"],
    illu: ["pushup_incline_up", "pushup_incline_down"],
  },
  "Pompes sur les genoux": {
    cat: "Pectoraux", unit: "reps",
    muscles: ["Pectoraux", "Triceps", "Épaules (avant)"],
    goal: "Apprendre le mouvement complet avec moins de charge — parfait pour ajouter du volume en fin de série.",
    rest: 60, tempo: "Descente 2 s · montée 1 s", breath: "Inspire en descendant, souffle en poussant",
    hands: "Un peu plus larges que les épaules, sous la poitrine.",
    feet: "Genoux au sol (sur un tissu plié), chevilles croisées.",
    back: "Ligne droite des genoux à la tête, bassin avancé.",
    steps: [
      "Mets-toi à genoux, mains au sol sous la poitrine.",
      "Avance le bassin pour aligner genoux, hanches et épaules.",
      "Descends la poitrine près du sol puis remonte en poussant.",
    ],
    errors: ["Fesses en arrière (le mouvement devient trop facile)", "Amplitude réduite"],
    safety: ["Mets un tissu sous les genoux si le sol est dur."],
    easier: "Pompes inclinées mains hautes.",
    harder: "Pompes classiques.",
    replacements: ["Pompes inclinées", "Pompes classiques"],
    illu: ["pushup_knee_up", "pushup_knee_down"],
  },
  "Pompes mains serrées": {
    cat: "Pectoraux", unit: "reps",
    muscles: ["Triceps", "Pectoraux (centre)", "Épaules (avant)"],
    goal: "Cibler les triceps et l'intérieur des pectoraux pour des bras plus dessinés.",
    rest: 75, tempo: "Descente 2 s · montée 1 s", breath: "Inspire en descendant, souffle en poussant",
    hands: "Sous la poitrine, écart plus étroit que les épaules (pas obligatoirement collées).",
    feet: "Comme une pompe classique.",
    back: "Planche rigide, coudes qui frôlent les côtes.",
    steps: [
      "Position de pompe, mains rapprochées sous la poitrine.",
      "Descends en gardant les coudes le long du corps.",
      "Pousse en serrant volontairement les triceps en haut.",
    ],
    errors: ["Coudes qui partent sur les côtés", "Mains trop collées (douleur poignets)"],
    safety: ["Si les poignets protestent, élargis un peu les mains ou passe sur support incliné."],
    easier: "Même exercice incliné sur un support.",
    harder: "Ralentis la descente à 3 secondes.",
    replacements: ["Pompes classiques", "Extension triceps au-dessus de la tête", "Dips sur chaise"],
    illu: ["pushup_up", "pushup_down"],
  },
  "Pompes déclinées": {
    cat: "Pectoraux", unit: "reps",
    muscles: ["Pectoraux (haut)", "Épaules (avant)", "Triceps"],
    goal: "Version difficile de la pompe : accentue le haut des pectoraux et les épaules.",
    rest: 90, tempo: "Descente 2 s · montée 1 s", breath: "Inspire en descendant, souffle en poussant",
    hands: "Largeur épaules +, sous les épaules.",
    feet: "Surélevés sur une chaise, une marche ou un banc stable.",
    back: "Planche stricte, ne laisse pas le bassin plonger.",
    steps: [
      "Pose les pieds sur un support stable (20–50 cm).",
      "Mains au sol, corps en planche inclinée tête vers le bas.",
      "Descends le front vers le sol en contrôlant, puis pousse fort.",
    ],
    errors: ["Bassin qui casse", "Descente trop rapide", "Support qui glisse"],
    safety: ["À faire seulement quand les pompes classiques sont propres sur toute la série."],
    easier: "Pompes classiques.",
    harder: "Ajoute le sac à dos lesté.",
    replacements: ["Pompes classiques", "Pompes lestées (sac à dos)"],
    illu: ["pushup_decline", "pushup_decline_down"],
  },
  "Pompes lestées (sac à dos)": {
    cat: "Pectoraux", unit: "reps",
    muscles: ["Pectoraux", "Triceps", "Épaules (avant)", "Tronc"],
    goal: "Continuer à progresser quand les pompes deviennent trop faciles : on ajoute de la charge.",
    rest: 90, tempo: "Descente 2–3 s · montée explosive", breath: "Inspire en descendant, souffle en poussant",
    hands: "Comme une pompe classique.",
    feet: "Comme une pompe classique.",
    back: "Planche très gainée : le sac ne doit pas faire creuser les lombaires.",
    steps: [
      "Mets un sac à dos chargé (livres, bouteilles) bien plaqué sur le haut du dos.",
      "Position de pompe classique, ventre très serré.",
      "Descends lentement puis pousse fort. Garde le sac stable.",
    ],
    errors: ["Sac posé trop bas (creuse les lombaires)", "Amplitude réduite à cause de la charge"],
    safety: ["Commence léger (2–4 kg) et augmente petit à petit.", "Stoppe si le bas du dos travaille plus que les pectoraux."],
    easier: "Pompes classiques sans sac.",
    harder: "Augmente la charge du sac ou ralentis la descente.",
    replacements: ["Pompes classiques", "Pompes déclinées"],
    illu: ["pushup_up", "pushup_down"],
  },

  /* ============ DOS ============ */
  "Tirage avec sac à dos": {
    cat: "Dos", unit: "reps",
    muscles: ["Grand dorsal", "Trapèzes", "Biceps", "Lombaires (statique)"],
    goal: "Épaissir le dos et améliorer la posture — indispensable pour équilibrer les pompes.",
    rest: 75, tempo: "Tire en 1 s · redescends en 2 s", breath: "Souffle en tirant, inspire en redescendant",
    hands: "Saisis les anses du sac, prise ferme, bras tendus au départ.",
    feet: "Largeur bassin, genoux légèrement fléchis.",
    back: "Buste penché vers l'avant (45–60°), dos plat et neutre — jamais arrondi.",
    steps: [
      "Charge le sac (livres, bouteilles d'eau).",
      "Penche le buste en avant, dos plat, genoux souples.",
      "Tire le sac vers le nombril en serrant les omoplates.",
      "Marque un temps en haut, redescends lentement bras tendus.",
    ],
    errors: ["Dos arrondi", "Tirer avec les bras sans serrer les omoplates", "Buste qui se redresse à chaque répétition", "Mouvement d'élan"],
    safety: ["Priorité au dos plat : réduis la charge si tu n'arrives plus à le tenir.", "Vu ton historique de dos fragile : échauffe-toi avec 10 répétitions sac léger."],
    easier: "Allège le sac ou pose une main sur un support (tirage un bras).",
    harder: "Alourdis le sac ou marque 2 s de pause en haut.",
    replacements: ["Tirage à un bras avec sac", "Superman (extensions dos)"],
    illu: ["row_down", "row_up"],
  },
  "Tirage à un bras avec sac": {
    cat: "Dos", unit: "par bras",
    muscles: ["Grand dorsal", "Trapèzes", "Biceps"],
    goal: "Travailler chaque côté du dos séparément, avec le dos bien protégé par l'appui.",
    rest: 60, tempo: "Tire en 1 s · redescends en 2 s", breath: "Souffle en tirant",
    hands: "Une main tient le sac, l'autre est posée sur une chaise ou un genou.",
    feet: "En fente légère, stable.",
    back: "Plat, parallèle au sol ou presque, regard vers le sol.",
    steps: [
      "Appuie une main sur une chaise, l'autre tient le sac bras tendu.",
      "Tire le sac vers la hanche en gardant le coude près du corps.",
      "Serre l'omoplate en haut, redescends lentement.",
      "Fais toutes les répétitions d'un côté puis change de bras.",
    ],
    errors: ["Rotation du buste pour aider", "Épaule qui monte vers l'oreille", "Dos arrondi"],
    safety: ["L'appui protège le bas du dos : parfait si tes lombaires sont sensibles."],
    easier: "Allège le sac.",
    harder: "Alourdis le sac, pause 2 s en haut.",
    replacements: ["Tirage avec sac à dos", "Superman (extensions dos)"],
    illu: ["row1_down", "row1_up"],
  },
  "Superman (extensions dos)": {
    cat: "Dos", unit: "reps",
    muscles: ["Lombaires", "Paravertébraux", "Fessiers", "Trapèzes"],
    goal: "Renforcer en douceur les muscles le long de la colonne — ta zone historiquement fragile.",
    rest: 45, tempo: "Monte en 2 s · tiens 2 s · redescends en 2 s", breath: "Souffle en montant, respire calmement en tenant",
    hands: "Bras tendus devant (plus dur) ou le long du corps (plus facile).",
    feet: "Tendus derrière, posés au sol ou légèrement levés.",
    back: "Allongé sur le ventre. Monte SANS à-coup, amplitude modérée.",
    steps: [
      "Allonge-toi sur le ventre, bras devant toi.",
      "Décolle doucement la poitrine et les bras de quelques centimètres.",
      "Tiens 2 secondes en serrant fessiers et dos, sans forcer sur la nuque.",
      "Redescends lentement. C'est un petit mouvement contrôlé, pas un grand pont.",
    ],
    errors: ["Monter trop haut et trop vite", "Tête en hyperextension", "Retenir sa respiration"],
    safety: ["Amplitude courte : quelques centimètres suffisent.", "Toute douleur vive dans la colonne = stop immédiat."],
    easier: "Bras le long du corps, décolle seulement la poitrine.",
    harder: "Bras tendus devant + jambes décollées, tiens 3–4 s.",
    replacements: ["Bird-dog", "Pont fessier"],
    illu: ["superman_down", "superman_up"],
  },

  /* ============ ÉPAULES ============ */
  "Développé au-dessus de la tête": {
    cat: "Épaules", unit: "reps",
    muscles: ["Épaules (deltoïdes)", "Triceps", "Trapèzes", "Tronc (statique)"],
    goal: "Construire des épaules larges — c'est TON exercice épaules principal, à la place du pike push-up.",
    rest: 75, tempo: "Pousse en 1 s · redescends en 2 s", breath: "Souffle en poussant vers le haut",
    hands: "Une bouteille dans chaque main (ou le sac tenu à deux mains), au niveau des épaules.",
    feet: "Largeur bassin, genoux très légèrement fléchis.",
    back: "Droit et gainé : serre le ventre et les fessiers pour ne pas creuser les lombaires.",
    steps: [
      "Debout, une bouteille dans chaque main à hauteur d'épaules, paumes vers l'avant.",
      "Serre le ventre, pousse les charges au-dessus de la tête jusqu'aux bras tendus.",
      "Les bras finissent près des oreilles, sans cambrer le dos.",
      "Redescends lentement jusqu'aux épaules et enchaîne.",
    ],
    errors: ["Creuser le bas du dos pour finir le mouvement", "Pousser devant soi au lieu d'au-dessus", "Épaules crispées vers les oreilles"],
    safety: ["Si le dos cambre, allège la charge ou fais-le assis dossier droit.", "Charge de départ conseillée : 2 bouteilles de 1,5 L."],
    easier: "Développé épaules assis (le dossier protège le dos), ou bouteilles plus petites.",
    harder: "Sac à dos tenu à deux mains, ou ralentis la descente à 3 s.",
    replacements: ["Développé épaules assis", "Élévations latérales", "Pike push-up surélevé"],
    illu: ["ohp_start", "ohp_up"],
  },
  "Développé épaules assis": {
    cat: "Épaules", unit: "reps",
    muscles: ["Épaules (deltoïdes)", "Triceps", "Trapèzes"],
    goal: "La même construction d'épaules, assis : impossible de tricher avec le dos.",
    rest: 75, tempo: "Pousse en 1 s · redescends en 2 s", breath: "Souffle en poussant",
    hands: "Une bouteille dans chaque main à hauteur d'épaules.",
    feet: "À plat au sol, largeur bassin.",
    back: "Collé au dossier de la chaise, ventre serré.",
    steps: [
      "Assieds-toi sur une chaise stable, dos contre le dossier.",
      "Bouteilles à hauteur d'épaules, paumes vers l'avant.",
      "Pousse au-dessus de la tête jusqu'aux bras tendus, redescends lentement.",
    ],
    errors: ["Décoller le dos du dossier", "Amplitude incomplète en haut"],
    safety: ["Excellent choix les jours où ton dos est fatigué du travail au bateau."],
    easier: "Bouteilles plus légères, ou élévations latérales.",
    harder: "Sac tenu à deux mains ou pause 1 s bras tendus.",
    replacements: ["Développé au-dessus de la tête", "Élévations latérales"],
    illu: ["ohp_seat_start", "ohp_seat_up"],
  },
  "Élévations latérales": {
    cat: "Épaules", unit: "reps",
    muscles: ["Épaules (deltoïde moyen)"],
    goal: "Élargir visuellement les épaules — l'exercice « carrure » par excellence.",
    rest: 60, tempo: "Monte en 1 s · redescends en 2–3 s", breath: "Souffle en montant",
    hands: "Une bouteille dans chaque main, bras le long du corps, coudes très légèrement fléchis.",
    feet: "Largeur bassin, stable.",
    back: "Droit, buste très légèrement penché en avant, ventre serré.",
    steps: [
      "Debout, une bouteille dans chaque main le long du corps.",
      "Monte les bras sur les côtés jusqu'à l'horizontale (pas plus haut).",
      "Les coudes guident le mouvement, poignets sous les coudes.",
      "Redescends lentement en freinant. C'est la descente qui construit l'épaule.",
    ],
    errors: ["Élan avec le buste", "Monter au-dessus de l'horizontale", "Épaules qui haussent vers les oreilles"],
    safety: ["Charge légère et propre : mieux vaut 15 répétitions parfaites que 8 avec élan."],
    easier: "Bouteilles plus petites ou bras fléchis à 90°.",
    harder: "Pause 2 s à l'horizontale ou maintien isométrique en fin de série.",
    replacements: ["Maintien bras en croix", "Développé au-dessus de la tête"],
    illu: ["lat_down", "lat_up"],
  },
  "Élévations frontales": {
    cat: "Épaules", unit: "reps",
    muscles: ["Épaules (deltoïde avant)"],
    goal: "Compléter l'avant de l'épaule avec une charge légère.",
    rest: 60, tempo: "Monte en 1 s · redescends en 2 s", breath: "Souffle en montant",
    hands: "Une bouteille dans chaque main devant les cuisses (ou une seule à deux mains).",
    feet: "Largeur bassin.",
    back: "Droit, ventre serré, pas d'élan.",
    steps: [
      "Debout, bouteilles devant les cuisses, bras presque tendus.",
      "Monte un bras (ou les deux) devant toi jusqu'à hauteur d'épaule.",
      "Redescends lentement sans balancer le buste.",
    ],
    errors: ["Élan du buste", "Monter trop haut", "Poignet cassé"],
    safety: ["Reste léger : cet exercice est un complément, pas un exercice principal."],
    easier: "Alterne un bras à la fois.",
    harder: "Pause 1 s en haut.",
    replacements: ["Élévations latérales", "Développé au-dessus de la tête"],
    illu: ["curl_down", "front_up"],
  },
  "Pike push-up surélevé": {
    cat: "Épaules", unit: "reps",
    muscles: ["Épaules", "Triceps", "Haut des pectoraux"],
    goal: "Version AMÉNAGÉE du pike push-up : mains sur un support surélevé, jambes quasi tendues sans forcer — beaucoup plus confortable que la version au sol.",
    rest: 90, tempo: "Descente 2 s · montée 1 s", breath: "Inspire en descendant, souffle en poussant",
    hands: "Sur un support solide (marche, banc, muret) largeur épaules.",
    feet: "Au sol, en arrière : plus les mains sont hautes, moins il faut plier les jambes.",
    back: "Bassin haut, dos droit, tête entre les bras — le corps forme un V renversé.",
    steps: [
      "Pose les mains sur un support à hauteur de genoux/hanches.",
      "Recule les pieds et monte les fesses : corps en V renversé, jambes souples.",
      "Plie les coudes pour amener le haut du crâne vers le support.",
      "Pousse pour revenir. Le support évite de devoir plier fortement les jambes.",
    ],
    errors: ["Dos arrondi", "Coudes qui partent en dehors", "Descendre trop vite"],
    safety: ["Optionnel : uniquement si la position est confortable. Sinon reste sur le développé bouteilles/sac, il travaille les mêmes muscles."],
    easier: "Support plus haut, ou développé au-dessus de la tête.",
    harder: "Support plus bas, pieds légèrement surélevés.",
    replacements: ["Développé au-dessus de la tête", "Développé épaules assis", "Élévations latérales"],
    illu: ["pike_box", "pike_box_down"],
  },
  "Maintien bras en croix": {
    cat: "Épaules", unit: "secondes",
    muscles: ["Épaules (deltoïdes)", "Trapèzes"],
    goal: "Brûler les épaules sans aucun matériel : tenir les bras à l'horizontale.",
    rest: 45, tempo: "Maintien statique", breath: "Respiration calme et régulière, ne bloque pas",
    hands: "Bras tendus en croix à l'horizontale, paumes vers le bas (bouteilles = plus dur).",
    feet: "Largeur bassin.",
    back: "Droit, ventre serré, épaules basses.",
    steps: [
      "Debout, monte les bras en croix à l'horizontale.",
      "Tiens la position sans laisser les bras descendre.",
      "Épaules loin des oreilles, respiration régulière.",
    ],
    errors: ["Bras qui descendent petit à petit", "Épaules crispées", "Respiration bloquée"],
    safety: ["Arrête quand la position n'est plus tenable proprement."],
    easier: "Réduis la durée.",
    harder: "Une petite bouteille dans chaque main.",
    replacements: ["Élévations latérales", "Développé au-dessus de la tête"],
    illu: ["iso_hold", "iso_hold"],
  },

  /* ============ BRAS ============ */
  "Curl biceps (bouteilles ou sac)": {
    cat: "Bras", unit: "reps",
    muscles: ["Biceps", "Avant-bras"],
    goal: "Des bras plus pleins — l'exercice plaisir qui se voit vite.",
    rest: 60, tempo: "Monte en 1 s · redescends en 2–3 s", breath: "Souffle en montant",
    hands: "Une bouteille dans chaque main (ou le sac à deux mains), paumes vers l'avant.",
    feet: "Largeur bassin, stable.",
    back: "Droit, coudes collés aux côtes, immobiles.",
    steps: [
      "Debout, charges le long du corps, paumes vers l'avant.",
      "Plie les coudes pour monter les charges vers les épaules.",
      "Les coudes ne bougent pas et ne s'écartent pas du corps.",
      "Redescends LENTEMENT (2–3 s) : c'est la descente qui fait grossir le bras.",
    ],
    errors: ["Élan avec le dos", "Coudes qui avancent", "Descente relâchée trop vite"],
    safety: ["Pas d'à-coups avec le bas du dos."],
    easier: "Allège, ou alterne un bras à la fois.",
    harder: "Alourdis le sac, ou descente en 4 s.",
    replacements: ["Tirage avec sac à dos", "Tirage à un bras avec sac"],
    illu: ["curl_down", "curl_up"],
  },
  "Extension triceps au-dessus de la tête": {
    cat: "Bras", unit: "reps",
    muscles: ["Triceps"],
    goal: "L'arrière du bras : c'est lui qui fait les deux tiers du volume du bras.",
    rest: 60, tempo: "Descente 2 s · montée 1 s", breath: "Souffle en tendant les bras",
    hands: "Une bouteille (ou le sac léger) tenue à deux mains derrière la tête.",
    feet: "Largeur bassin, ou assis sur une chaise.",
    back: "Droit, ventre serré, coudes qui pointent vers le plafond.",
    steps: [
      "Tiens une bouteille à deux mains au-dessus de la tête.",
      "Plie les coudes pour descendre la charge derrière la nuque.",
      "Les coudes restent serrés et pointés vers le haut.",
      "Tends les bras en serrant les triceps.",
    ],
    errors: ["Coudes qui s'écartent", "Dos qui cambre", "Descente trop rapide près de la tête"],
    safety: ["Mouvement contrôlé : la charge passe près de la tête."],
    easier: "Charge plus légère ou pompes mains serrées inclinées.",
    harder: "Charge plus lourde, descente 3 s.",
    replacements: ["Pompes mains serrées", "Dips sur chaise"],
    illu: ["tri_bent", "tri_ext"],
  },
  "Dips sur chaise": {
    cat: "Bras", unit: "reps",
    muscles: ["Triceps", "Pectoraux (bas)", "Épaules (avant)"],
    goal: "Triceps et pectoraux avec une simple chaise stable.",
    rest: 75, tempo: "Descente 2 s · montée 1 s", breath: "Inspire en descendant, souffle en poussant",
    hands: "Au bord de la chaise, doigts vers l'avant, bras tendus.",
    feet: "Posés devant, jambes fléchies (facile) ou tendues (dur).",
    back: "Près de la chaise, épaules basses, descends droit.",
    steps: [
      "Assieds-toi au bord d'une chaise, mains au bord de l'assise.",
      "Avance les fesses dans le vide, jambes fléchies devant.",
      "Plie les coudes pour descendre (coudes vers l'arrière, pas sur les côtés).",
      "Descends jusqu'à ~90° de flexion puis remonte en poussant.",
    ],
    errors: ["Épaules qui remontent vers les oreilles", "Descendre trop bas (douleur épaule)", "Chaise instable"],
    safety: ["Cale la chaise contre un mur.", "Si l'avant de l'épaule pince : réduis l'amplitude ou remplace."],
    easier: "Jambes très fléchies, amplitude réduite.",
    harder: "Jambes tendues, ou pieds surélevés.",
    replacements: ["Pompes mains serrées", "Extension triceps au-dessus de la tête"],
    illu: ["dips_up", "dips_down"],
  },

  /* ============ JAMBES ============ */
  "Squats": {
    cat: "Jambes", unit: "reps",
    muscles: ["Quadriceps", "Fessiers", "Tronc"],
    goal: "La base des jambes : force, fessiers et dépense calorique.",
    rest: 75, tempo: "Descente 2 s · montée 1 s", breath: "Inspire en descendant, souffle en montant",
    hands: "Bras tendus devant toi pour l'équilibre.",
    feet: "Largeur épaules, pointes légèrement ouvertes, talons au sol.",
    back: "Droit, poitrine fière, regard devant.",
    steps: [
      "Debout, pieds largeur épaules, pointes légèrement ouvertes.",
      "Pousse les fesses en arrière et plie les genoux, bras devant.",
      "Descends jusqu'à cuisses parallèles au sol (ou ta profondeur confortable).",
      "Pousse dans les talons pour remonter en serrant les fessiers.",
    ],
    errors: ["Talons qui décollent", "Genoux qui rentrent en dedans", "Dos qui s'arrondit en bas", "Descente trop courte"],
    safety: ["Genoux dans l'axe des pointes de pieds."],
    easier: "Squat sur chaise : assieds-toi puis relève-toi.",
    harder: "Squats avec sac à dos, ou descente en 3 s.",
    replacements: ["Squats avec sac à dos", "Fentes arrière", "Chaise contre le mur"],
    illu: ["stand", "squat_down"],
  },
  "Squats avec sac à dos": {
    cat: "Jambes", unit: "reps",
    muscles: ["Quadriceps", "Fessiers", "Tronc"],
    goal: "Le squat chargé : la progression naturelle quand le squat libre devient facile.",
    rest: 90, tempo: "Descente 2 s · montée 1 s", breath: "Inspire en descendant, souffle en montant",
    hands: "Sac à dos sur les épaules (bretelles serrées) ou serré contre la poitrine.",
    feet: "Largeur épaules, talons au sol.",
    back: "Droit et gainé, le sac ne doit pas te tirer en avant.",
    steps: [
      "Enfile le sac chargé, bretelles serrées.",
      "Même mouvement que le squat classique, buste droit.",
      "Descends contrôlé, remonte en poussant dans les talons.",
    ],
    errors: ["Buste qui bascule en avant", "Talons qui décollent", "Demi-amplitude"],
    safety: ["Augmente la charge progressivement (1–2 kg à la fois)."],
    easier: "Squats sans charge.",
    harder: "Alourdis le sac ou tempo 3 s de descente.",
    replacements: ["Squats", "Fentes arrière"],
    illu: ["stand_bag", "squat_down_bag"],
  },
  "Fentes arrière": {
    cat: "Jambes", unit: "par jambe",
    muscles: ["Quadriceps", "Fessiers", "Équilibre / tronc"],
    goal: "Jambes et fessiers, une jambe à la fois — plus doux pour les genoux que la fente avant.",
    rest: 75, tempo: "Descente 2 s · montée 1 s", breath: "Inspire en descendant, souffle en montant",
    hands: "Sur les hanches ou le long du corps (bouteilles = plus dur).",
    feet: "Un grand pas en ARRIÈRE, le talon avant reste bien au sol.",
    back: "Droit, buste vertical, regard devant.",
    steps: [
      "Debout, fais un grand pas en arrière avec une jambe.",
      "Descends le genou arrière vers le sol sans le cogner.",
      "Le genou avant reste au-dessus de la cheville.",
      "Pousse sur la jambe avant pour revenir debout. Alterne ou enchaîne d'un côté.",
    ],
    errors: ["Pas trop court (genou qui dépasse loin devant)", "Buste penché", "Perte d'équilibre (pose une main sur un mur)"],
    safety: ["Tiens un mur ou une chaise si l'équilibre est difficile au début."],
    easier: "Amplitude réduite, main sur un support.",
    harder: "Bouteilles en main ou sac sur le dos.",
    replacements: ["Squats", "Pont fessier une jambe"],
    illu: ["stand", "lunge_down"],
  },
  "Soulevé de terre roumain (sac)": {
    cat: "Jambes", unit: "reps",
    muscles: ["Ischio-jambiers", "Fessiers", "Lombaires (statique)"],
    goal: "L'arrière des jambes et les fessiers, en apprenant à plier les hanches dos plat — précieux pour ton dos.",
    rest: 90, tempo: "Descente 3 s · remontée 1–2 s", breath: "Inspire en descendant, souffle en remontant",
    hands: "Sac tenu à deux mains devant les cuisses, bras tendus.",
    feet: "Largeur bassin, genoux légèrement fléchis (angle fixe).",
    back: "PLAT du début à la fin — c'est LA règle de cet exercice.",
    steps: [
      "Debout, sac devant les cuisses, genoux légèrement fléchis.",
      "Pousse les fesses loin en ARRIÈRE en penchant le buste, dos plat.",
      "Le sac descend le long des cuisses jusqu'à sentir l'étirement derrière les jambes.",
      "Remonte en serrant les fessiers, sans tirer avec le dos.",
    ],
    errors: ["Dos qui s'arrondit", "Plier les genoux comme un squat", "Descendre trop bas", "Charge trop lourde trop tôt"],
    safety: ["Commence léger pour apprendre le mouvement.", "Toute douleur lombaire vive = stop et signale-la dans l'app."],
    easier: "Sans charge, mains glissant sur les cuisses.",
    harder: "Sac plus lourd, descente plus lente.",
    replacements: ["Pont fessier", "Pont fessier une jambe"],
    illu: ["stand_bag", "rdl_hinge"],
  },
  "Pont fessier": {
    cat: "Jambes", unit: "reps",
    muscles: ["Fessiers", "Ischio-jambiers", "Lombaires (doux)"],
    goal: "Réveiller et construire les fessiers, protéger le bas du dos. Parfait pour toi.",
    rest: 45, tempo: "Monte en 1 s · serre 2 s en haut · redescends en 2 s", breath: "Souffle en montant",
    hands: "Le long du corps, paumes au sol.",
    feet: "À plat, proches des fesses, largeur bassin.",
    back: "Allongé sur le dos ; en haut, le corps est aligné genoux-bassin-épaules, sans cambrer.",
    steps: [
      "Allongé sur le dos, pieds proches des fesses.",
      "Pousse dans les talons et monte le bassin en serrant les fessiers.",
      "En haut : ligne droite épaules-bassin-genoux, serre fort 2 secondes.",
      "Redescends lentement sans reposer complètement, puis enchaîne.",
    ],
    errors: ["Cambrer le dos au lieu de serrer les fessiers", "Pousser sur la pointe des pieds", "Monter trop haut"],
    safety: ["C'est le fessier qui travaille, pas les lombaires : si tu sens le bas du dos, réduis la hauteur."],
    easier: "Réduis l'amplitude ou la durée de maintien.",
    harder: "Pont une jambe ou sac posé sur le bassin.",
    replacements: ["Pont fessier une jambe", "Soulevé de terre roumain (sac)"],
    illu: ["bridge_down", "bridge_up"],
  },
  "Pont fessier une jambe": {
    cat: "Jambes", unit: "par jambe",
    muscles: ["Fessiers", "Ischio-jambiers", "Tronc"],
    goal: "La version difficile du pont : chaque fessier travaille seul, le bassin apprend à rester stable.",
    rest: 60, tempo: "Monte en 1 s · serre 1–2 s · redescends en 2 s", breath: "Souffle en montant",
    hands: "Le long du corps.",
    feet: "Un pied au sol près des fesses, l'autre jambe tendue vers le plafond ou l'horizontale.",
    back: "Bassin bien horizontal : il ne doit pas basculer d'un côté.",
    steps: [
      "Position de pont, une jambe tendue devant toi.",
      "Pousse dans le talon au sol et monte le bassin.",
      "Garde le bassin parfaitement horizontal, serre en haut.",
      "Redescends lentement. Fais toute la série puis change de jambe.",
    ],
    errors: ["Bassin qui penche du côté de la jambe levée", "Amplitude écourtée", "À-coups"],
    safety: ["Si le bassin bascule, reviens au pont à deux jambes."],
    easier: "Pont fessier classique.",
    harder: "Pause 3 s en haut de chaque répétition.",
    replacements: ["Pont fessier", "Soulevé de terre roumain (sac)"],
    illu: ["bridge_down", "bridge1_up"],
  },
  "Mollets debout": {
    cat: "Jambes", unit: "reps",
    muscles: ["Mollets"],
    goal: "Des mollets dessinés et des chevilles solides pour le travail debout sur le bateau.",
    rest: 40, tempo: "Monte en 1 s · tiens 1 s en haut · descends en 2 s", breath: "Respiration libre",
    hands: "Une main sur un mur pour l'équilibre.",
    feet: "Largeur bassin ; sur une marche pour plus d'amplitude.",
    back: "Droit, jambes tendues sans verrouiller.",
    steps: [
      "Debout, main sur un mur.",
      "Monte sur la pointe des pieds le plus haut possible.",
      "Tiens 1 seconde en haut, redescends lentement.",
      "Sur une marche : laisse les talons descendre sous le niveau pour l'étirement.",
    ],
    errors: ["Rebondir", "Amplitude minuscule", "Vitesse excessive"],
    safety: ["Sur une marche, tiens-toi bien."],
    easier: "À plat au sol, deux jambes.",
    harder: "Sur une jambe, ou avec le sac à dos.",
    replacements: ["Squats", "Chaise contre le mur"],
    illu: ["calf_flat", "calf_up"],
  },
  "Chaise contre le mur": {
    cat: "Jambes", unit: "secondes",
    muscles: ["Quadriceps", "Fessiers"],
    goal: "Endurance des cuisses sans aucun impact ni matériel.",
    rest: 60, tempo: "Maintien statique", breath: "Respiration régulière, ne bloque pas",
    hands: "Le long du mur ou sur les cuisses (pas sur les genoux).",
    feet: "À plat, largeur bassin, avancés pour que les genoux soient au-dessus des chevilles.",
    back: "Entièrement collé au mur, cuisses parallèles au sol.",
    steps: [
      "Adosse-toi à un mur et descends comme assis sur une chaise invisible.",
      "Cuisses parallèles au sol, genoux à 90° au-dessus des chevilles.",
      "Tiens la position en respirant calmement.",
    ],
    errors: ["Genoux au-delà des pointes de pieds", "Mains en appui sur les genoux", "Position trop haute"],
    safety: ["Arrête si les genoux deviennent douloureux (autre chose que la brûlure des cuisses)."],
    easier: "Position plus haute (moins plié).",
    harder: "Position stricte à 90° plus longtemps, ou sac sur les cuisses.",
    replacements: ["Squats", "Fentes arrière"],
    illu: ["stand", "wallsit"],
  },

  /* ============ TRONC ============ */
  "Gainage (planche)": {
    cat: "Tronc", unit: "secondes",
    muscles: ["Abdominaux profonds", "Tronc complet", "Épaules"],
    goal: "Un ventre plus plat et un dos protégé : le gainage tient tout le reste.",
    rest: 45, tempo: "Maintien statique", breath: "Respiration calme, ne bloque JAMAIS",
    hands: "Sur les avant-bras, coudes sous les épaules.",
    feet: "Sur les pointes, largeur bassin.",
    back: "Ligne droite tête-bassin-talons ; bascule légèrement le bassin pour effacer le creux lombaire.",
    steps: [
      "En appui sur les avant-bras et les pointes de pieds.",
      "Serre le ventre et les fessiers : le corps est une planche.",
      "Regarde le sol, nuque neutre, respire calmement.",
      "Arrête dès que le bassin commence à tomber : une planche cassée ne compte pas.",
    ],
    errors: ["Bassin qui tombe (lombaires en danger)", "Fesses trop hautes", "Respiration bloquée", "Tête relevée"],
    safety: ["Mieux vaut 3 × 20 s parfaites qu'une minute cassée.", "Douleur bas du dos = stop, passe sur les genoux."],
    easier: "Planche sur les genoux.",
    harder: "Lève un pied 5 s en alternance, ou allonge la durée.",
    replacements: ["Dead bug", "Gainage latéral (genoux)"],
    illu: ["plank", "plank"],
  },
  "Gainage latéral (genoux)": {
    cat: "Tronc", unit: "secondes/côté",
    muscles: ["Obliques", "Tronc latéral", "Hanche"],
    goal: "Les obliques : la taille et les fameuses poignées d'amour — version genoux, adaptée à la reprise.",
    rest: 40, tempo: "Maintien statique", breath: "Respiration régulière",
    hands: "Avant-bras au sol sous l'épaule ; l'autre main sur la hanche ou vers le ciel.",
    feet: "Genoux pliés au sol, l'un sur l'autre.",
    back: "Corps aligné épaule-bassin-genoux, hanche haute.",
    steps: [
      "Allonge-toi sur le côté, appui sur l'avant-bras, coude sous l'épaule.",
      "Genoux pliés, décolle la hanche du sol.",
      "Aligne épaule-bassin-genoux et tiens la position.",
      "Change de côté après le repos.",
    ],
    errors: ["Hanche qui retombe", "Épaule qui s'écrase (pousse le sol)", "Bassin en avant ou en arrière"],
    safety: ["Coude bien sous l'épaule pour la protéger."],
    easier: "Réduis la durée.",
    harder: "Jambes tendues (gainage latéral complet).",
    replacements: ["Gainage (planche)", "Dead bug"],
    illu: ["sideplank_knee", "sideplank_knee"],
  },
  "Dead bug": {
    cat: "Tronc", unit: "par côté",
    muscles: ["Abdominaux profonds (transverse)", "Coordination"],
    goal: "Le meilleur exercice d'abdos pour un dos fragile : ventre fort, lombaires plaqués, zéro risque.",
    rest: 45, tempo: "Étends en 2 s · reviens en 2 s", breath: "Souffle LONGUEMENT en étendant bras et jambe",
    hands: "Bras tendus vers le plafond au départ.",
    feet: "Hanches et genoux à 90°, tibias parallèles au sol.",
    back: "Bas du dos PLAQUÉ au sol pendant tout le mouvement — c'est le seul vrai objectif.",
    steps: [
      "Allongé sur le dos, bras vers le plafond, jambes à 90°.",
      "Plaque le bas du dos au sol en serrant le ventre.",
      "Étends LENTEMENT le bras droit derrière la tête et la jambe gauche devant.",
      "Reviens, puis change de côté. Le dos ne décolle jamais.",
    ],
    errors: ["Bas du dos qui se creuse (réduis l'amplitude)", "Mouvement trop rapide", "Respiration bloquée"],
    safety: ["Si le dos décolle, n'étends pas complètement la jambe : amplitude courte d'abord."],
    easier: "Étends seulement la jambe, gardes les bras fixes.",
    harder: "Étends bras et jambe au ras du sol, pause 2 s.",
    replacements: ["Gainage (planche)", "Bird-dog"],
    illu: ["deadbug_start", "deadbug_ext"],
  },
  "Bird-dog": {
    cat: "Tronc", unit: "par côté",
    muscles: ["Lombaires profonds", "Fessiers", "Équilibre", "Abdominaux"],
    goal: "Stabiliser la colonne et renforcer les paravertébraux en douceur — sur mesure pour ton dos.",
    rest: 45, tempo: "Étends en 2 s · tiens 2 s · reviens en 2 s", breath: "Souffle en étendant",
    hands: "À quatre pattes, mains sous les épaules.",
    feet: "Genoux sous les hanches.",
    back: "Neutre et immobile : imagine un verre d'eau posé sur tes lombaires.",
    steps: [
      "À quatre pattes, dos neutre, ventre serré.",
      "Étends en même temps le bras droit devant et la jambe gauche derrière.",
      "Tiens 2 secondes sans que le bassin bascule.",
      "Reviens lentement et change de côté.",
    ],
    errors: ["Bassin qui tourne", "Dos qui se creuse en étendant", "Jambe montée trop haut", "Mouvement précipité"],
    safety: ["Amplitude modérée : la jambe finit à l'horizontale, pas plus haut."],
    easier: "Étends seulement la jambe (sans le bras).",
    harder: "Tiens 4–5 s, ou coude-genou qui se touchent entre les répétitions.",
    replacements: ["Dead bug", "Superman (extensions dos)"],
    illu: ["birddog_start", "birddog_ext"],
  },
};

/* utilitaires bibliothèque */
const exByCat = (cat) => Object.keys(EXOS).filter((n) => EXOS[n].cat === cat);
const exInfo = (name) => EXOS[name] || null;
const exUnit = (name) => (EXOS[name] ? EXOS[name].unit : "reps");
const isTimeUnit = (name) => /sec/i.test(exUnit(name));
